name: BIMEnv39
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - python=3.9
  - plotly
  - ipykernel
  - pythonocc-core=7.7.0
  - pythreejs
  - pyside2
  - pyqt=5.15.7
  - lark
  - ifcopenshell