name: BIMEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pythonocc-core=7.7.0
  - plotly
  - ifcopenshell
  - ipykernel
  - pandas
  - pythreejs
  - lark
  - pyqt
  - pyside2
  - scipy