name: BIMEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - conda
  - conda-build
  # - python=3.11.5
  - python=3.11
  - ifcopenshell=v0.7.0a10
  # - pythonocc-core=7.7.0
  - pythonocc-core=7
  - plotly
  - ipykernel
  - pandas
  - pythreejs
  - lark
  - pyqt
  - pyqt5-sip
  - pyside2
  - scipy
  - deprecated
  - pillow
  - pytest
  - flake8
  - sphinx
  - pip:
    - PyniteFEA
    - sphinx-press-theme
    - sphinx-book-theme
